Repository particl/particl-desktop, pull requests merged in 2018-05, with the labels that each got.

#977 additional info added on shipping status
  src/app/core/market/api/template/template.model.ts
  src/app/market/shared/orders/order-item/order-item.component.html
Labels: ready for review

#989 - Fixed: (MP: #981) : The grammer error on ordering workflow
  src/app/market/buy/checkout-process/checkout-process.component.html
Labels: ready for review

#991 - Fixed: The stepper issue related to the caching mechanism on the order checkout process
  src/app/core/market/api/profile/profile.service.ts
  src/app/core/market/market-cache/checkout-process-cache.service.spec.ts
  src/app/core/market/market-cache/checkout-process-cache.service.ts
  src/app/core/market/market-cache/market-cache.module.ts
  src/app/market/buy/checkout-process/checkout-process.component.html
  src/app/market/buy/checkout-process/checkout-process.component.ts
  src/app/market/sell/add-item/add-item.component.html
  src/app/market/sell/add-item/add-item.component.scss
  src/app/market/sell/sell.component.html
  src/app/modals/place-order/place-order.component.html
Labels: ready for review

#986 Hide the “Add to Cart” button if a bid has been placed on an item by …
  src/app/core/market/api/bid/bid.model.ts
  src/app/core/market/api/cart/cart.service.ts
  src/app/core/market/api/template/template.model.ts
  src/app/core/market/market-cache/add-to-cart-cache.service.spec.ts
  src/app/core/market/market-cache/add-to-cart-cache.service.ts
  src/app/core/market/market-cache/market-cache.module.ts
  src/app/core/market/market-state/market-state.service.ts
  src/app/market/listings/listing-item/listing-item.component.html
  src/app/market/listings/listing-item/listing-item.component.ts
  src/app/market/listings/listings.component.ts
  src/app/market/listings/preview-listing/preview-listing.component.html
  src/app/market/listings/preview-listing/preview-listing.component.scss
  src/app/market/listings/preview-listing/preview-listing.component.ts
  src/app/market/market.module.ts
  src/app/market/sell/add-item/add-item.component.html
  src/app/market/sell/add-item/add-item.component.scss
  src/app/market/shared/addtocart/add-to-cart.component.html
  src/app/market/shared/addtocart/add-to-cart.component.scss
  src/app/market/shared/addtocart/add-to-cart.component.spec.ts
  src/app/market/shared/addtocart/add-to-cart.component.ts
  src/app/market/shared/favorite/favorite.component.html
  src/app/market/shared/favorite/favorite.component.scss
  src/app/market/shared/favorite/favorite.component.ts
  src/app/market/shared/orders/orders.component.ts
Labels: ready for review

#1000 Market seller active listings issues
  src/app/market/listings/listings.component.ts
  src/app/market/sell/sell.component.html
  src/app/market/sell/sell.component.spec.ts
  src/app/market/sell/sell.component.ts
Labels: market, ready for review

#1009 Seller scrollbar
  src/app/market/listings/listings.component.ts
  src/app/market/sell/sell.component.html
  src/app/market/sell/sell.component.spec.ts
  src/app/market/sell/sell.component.ts
Labels: ready for review

#1014 error handling while bidding on order according to scenarios
  src/app/core/market/api/bid/bid.service.ts
  src/app/market/buy/checkout-process/checkout-process.component.ts
Labels: ready for review

#994 fix shipping,domestic,internationl,total and escrow prices according …
  src/app/core/market/api/bid/bid.model.ts
  src/app/core/market/api/cart/cart.model.ts
  src/app/core/market/api/listing/listing.model.ts
  src/app/core/market/api/template/template.model.ts
  src/app/market/buy/checkout-process/checkout-process.component.html
  src/app/market/buy/checkout-process/checkout-process.component.ts
  src/app/market/listings/preview-listing/preview-listing.component.html
  src/app/market/shared/orders/order-item/order-item.component.html
  src/app/market/shared/orders/order-item/order-item.component.ts
  src/app/wallet/wallet/send/send-confirmation-modal/send-confirmation-modal.component.html
  src/app/wallet/wallet/send/send-confirmation-modal/send-confirmation-modal.component.ts
Labels: ready for review

#1013 Disable click on Shipping details if cart is empty. #1010
  src/app/market/buy/checkout-process/checkout-process.component.ts
Labels: market, ready for review

#1021 remove item once it get bidded from the cart
  src/app/core/market/api/bid/bid.service.spec.ts
  src/app/core/market/api/bid/bid.service.ts
  src/app/core/market/api/cart/cart.service.spec.ts
  src/app/core/market/api/cart/cart.service.ts
  src/app/market/buy/checkout-process/checkout-process.component.ts
  src/app/market/shared/addtocart/add-to-cart.component.ts
Labels: ready for review

#1022 favourite service refactor to take dynamic profile
  src/app/core/market/api/favorites/favorites.service.ts
  src/app/core/market/api/profile/profile.service.ts
  src/app/core/market/market-state/market-state.service.ts
Labels: ready for review

#1024 handle reject order status and disable complete order action button
  src/app/core/util/utils.ts
  src/app/market/_lists-shared.scss
  src/app/market/shared/orders/order-item/order-item.component.ts
Labels: ready for review

#903 fix parameters passed to core
  modules/logger.js
Labels: High Priority, bug
