Repository particl/particl-desktop, pull requests merged in 2018-02, with the labels that each got.

#797 Rpc state refactor
  src/app/_test/core-test/core-test.module.ts
  src/app/_test/core-test/rpc-test/mock-data/getpeerinfo.mock.ts
  src/app/_test/core-test/rpc-test/rpc-mock.service.ts
  src/app/_test/core-test/rpc-test/rpc-test.module.ts
  src/app/app.component.ts
  src/app/core-ui/main/main-view.component.html
  src/app/core-ui/main/main-view.component.ts
  src/app/core-ui/main/status/modal/help-modal/console-modal.component.ts
  src/app/core-ui/main/status/status.component.ts
  src/app/core/core.module.ts
  src/app/core/rpc/blockstatus/blockstatus.service.ts
  src/app/core/rpc/new-tx-notifier/new-tx-notifier.service.ts
  src/app/core/rpc/rpc-state/rpc-state.class.ts
  src/app/core/rpc/rpc-state/rpc-state.service.spec.ts
  src/app/core/rpc/rpc-state/rpc-state.service.ts
  src/app/core/rpc/rpc.module.ts
  src/app/core/rpc/rpc.service.ts
  src/app/core/state/state.service.ts
  src/app/core/window/window.service.spec.ts
  src/app/core/window/window.service.ts
  src/app/modals/coldstake/coldstake.component.ts
  src/app/modals/createwallet/createwallet.component.ts
  src/app/modals/encryptwallet/encryptwallet.component.ts
  src/app/modals/modals.component.ts
  src/app/modals/modals.service.ts
  src/app/modals/shared/password/password.component.ts
  src/app/modals/syncing/syncing.component.ts
  src/app/wallet/overview/widgets/coldstake/coldstake.component.ts
  src/app/wallet/overview/widgets/coldstake/revert-coldstaking/revert-coldstaking.component.ts
  src/app/wallet/overview/widgets/coldstake/zap-coldstaking/zap-coldstaking.component.ts
  src/app/wallet/overview/widgets/stakinginfo/stakinginfo.component.ts
  src/app/wallet/wallet/address-book/modal/new-address-modal/new-address-modal.component.ts
  src/app/wallet/wallet/addresslookup/addresslookup.component.ts
  src/app/wallet/wallet/balances/balance.component.spec.ts
  src/app/wallet/wallet/balances/balance.component.ts
  src/app/wallet/wallet/receive/modals/add-address-label/add-address-label.component.ts
  src/app/wallet/wallet/send/fix-wallet-modal/fix-wallet-modal.component.ts
  src/app/wallet/wallet/send/send.component.html
  src/app/wallet/wallet/send/send.component.spec.ts
  src/app/wallet/wallet/send/send.component.ts
  src/app/wallet/wallet/send/send.service.ts
  src/app/wallet/wallet/shared/address-table/address-table.component.ts
  src/app/wallet/wallet/shared/signature-address-modal/signature-address-modal.component.ts
  src/app/wallet/wallet/shared/transaction.service.ts
Labels: Code Optimization, ready for review

#837 Adds new angularx-qrcode in qr-code-modal
  src/app/wallet/wallet/shared/qr-code-modal/qr-code-modal.component.html
  src/assets/theme.scss
  src/styles.scss
Labels: ready for review

#828 focus on input when debug console open
  src/app/app.module.ts
  src/app/core-ui/directive/common.directives.ts
  src/app/core-ui/directive/directive.module.ts
  src/app/core-ui/main/main-view.module.ts
  src/app/core-ui/main/status/modal/help-modal/console-modal.component.html
  src/app/modals/createwallet/passphrase/passphrase.component.spec.ts
  src/app/modals/modals.module.ts
Labels: ready for review

#840 fix label issue and address book page update
  src/app/wallet/wallet/send/send.component.ts
  src/app/wallet/wallet/shared/address-table/address-table.component.ts
  src/app/wallet/wallet/shared/address.service.ts
Labels: ready for review

#846 Fix/coldstake issues
  src/app/wallet/overview/overview.component.ts
  src/app/wallet/overview/widgets/coldstake/coldstake.component.html
  src/app/wallet/overview/widgets/coldstake/coldstake.component.spec.ts
  src/app/wallet/overview/widgets/coldstake/coldstake.component.ts
  src/app/wallet/overview/widgets/coldstake/coldstake.service.spec.ts
  src/app/wallet/overview/widgets/coldstake/coldstake.service.ts
  src/app/wallet/overview/widgets/coldstake/revert-coldstaking/revert-coldstaking.component.html
  src/app/wallet/overview/widgets/coldstake/revert-coldstaking/revert-coldstaking.component.ts
  src/app/wallet/wallet.module.ts
  src/app/wallet/wallet/wallet.module.ts
Labels: needs-testing, ready for review

#862 market-api
  main.js
  modules/daemon/daemon.js
  modules/options.js
  modules/webrequest/http-auth.js
  src/app/core-ui/main/main-view.component.ts
  src/app/core/core.module.ts
  src/app/core/market/api/category/category.model.ts
  src/app/core/market/api/category/category.service.spec.ts
  src/app/core/market/api/category/category.service.ts
  src/app/core/market/api/profile/profile.service.spec.ts
  src/app/core/market/api/profile/profile.service.ts
  src/app/core/market/api/template/template.service.spec.ts
  src/app/core/market/api/template/template.service.ts
  src/app/core/market/market-state/market-state.service.spec.ts
  src/app/core/market/market-state/market-state.service.ts
  src/app/core/market/market.module.ts
  src/app/core/market/market.service.spec.ts
  src/app/core/market/market.service.ts
  src/app/core/rpc/rpc.service.ts
  src/app/market/overview-listings/overview-listings.component.html
  src/app/market/overview-listings/overview-listings.component.ts
  src/app/market/sell/add-item/add-item.component.html
  src/app/market/sell/add-item/add-item.component.ts
Labels: PRG, market
