Repository particl/particl-desktop, pull requests merged in 2018-06, with the labels that each got.

#1039 moved seller-listing seperate component for showing listing
  src/app/market/market.module.ts
  src/app/market/sell/sell.component.html
  src/app/market/sell/sell.component.ts
  src/app/market/sell/seller-listing/seller-listing.component.html
  src/app/market/sell/seller-listing/seller-listing.component.scss
  src/app/market/sell/seller-listing/seller-listing.component.spec.ts
  src/app/market/sell/seller-listing/seller-listing.component.ts
Labels: ready for review

#1060 CSS reorg. & clean-up
  src/app/market/sell/sell.component.html
  src/app/market/shared/orders/orders.component.html
  src/app/wallet/wallet/addresslookup/addresslookup.component.html
  src/app/wallet/wallet/shared/signature-address-modal/signature-address-modal.component.html
  src/assets/_config.scss
  src/assets/scss/_helper.scss
  src/assets/scss/_material-components.scss
  src/assets/theme.scss
  src/styles.scss
Labels: GFX, enhancement

#1068 Receive page 2.0
  src/app/wallet/wallet/receive/receive.component.html
  src/app/wallet/wallet/receive/receive.component.scss
  src/app/wallet/wallet/receive/receive.component.ts
  src/app/wallet/wallet/send/send.component.html
  src/assets/_config.scss
Labels: GFX, enhancement, ready for review

#1047 fixed double quote and single quote values - https://particl.atlassian.net/browse/PD-154
  src/app/core-ui/main/status/modal/help-modal/console-modal.component.spec.ts
  src/app/core-ui/main/status/modal/help-modal/console-modal.component.ts
  src/app/core/rpc/rpc.service.ts
Labels: ready for review

#1055 close preview listing modal after add to cart -https://particl.atlassian.net/browse/PD-138
  src/app/core/market/market.service.ts
  src/app/market/listings/preview-listing/preview-listing.component.html
  src/app/market/shared/addtocart/add-to-cart.component.ts
Labels: ready for review

#1048 Shipping addresses filter and fixing related to it - https://particl.atlassian.net/browse/PD-157
  src/app/core/market/api/cart/cart.service.ts
  src/app/core/market/api/profile/profile.model.ts
  src/app/core/market/api/profile/profile.service.ts
  src/app/market/buy/checkout-process/checkout-process.component.html
  src/app/market/buy/checkout-process/checkout-process.component.ts
Labels: ready for review

#1042 handle accpet bid error - https://particl.atlassian.net/browse/PD-151
  src/app/core/market/api/bid/bid.service.ts
  src/app/core/market/market.service.ts
Labels: ready for review

#1061 resolve the shipping address issue and created common component for shipping address - https://particl.atlassian.net/browse/PD-144
  src/app/market/buy/checkout-process/checkout-process.component.html
  src/app/market/buy/checkout-process/checkout-process.component.ts
  src/app/market/market.module.ts
  src/app/market/shared/orders/order-item/order-item.component.html
  src/app/market/shared/shipping-address/shipping-address.component.html
  src/app/market/shared/shipping-address/shipping-address.component.scss
  src/app/market/shared/shipping-address/shipping-address.component.spec.ts
  src/app/market/shared/shipping-address/shipping-address.component.ts
Labels: ready for review

#1050 Markeplace debug window - https://particl.atlassian.net/browse/PD-153
  src/app/core-ui/main/status/modal/help-modal/console-modal.component.html
  src/app/core-ui/main/status/modal/help-modal/console-modal.component.ts
  src/app/core/market/market.module.ts
  src/assets/theme.scss
Labels: ready for review

#1069 Gfx/receive labels
  src/app/wallet/wallet/receive/receive.component.html
  src/app/wallet/wallet/receive/receive.component.scss
  src/app/wallet/wallet/receive/receive.component.ts
Labels: enhancement, ready for review

#1082 Fixed log (console) error.
  src/app/core/http/client-version.service.ts
Labels: ready for review
