Repository particl/particl-desktop, pull requests merged in 2018-07, with the labels that each got.

#1095 Sidebar menu tweaks
  src/app/core-ui/main/main-view.component.html
  src/app/core-ui/main/main-view.component.scss
  src/app/modals/shared/percentage-bar/percentage-bar.component.html
  src/app/modals/shared/percentage-bar/percentage-bar.component.scss
  src/assets/_config.scss
Labels: GFX, ready for review

#1073 Added prefix to market related modals folders
  src/app/market/buy/checkout-process/checkout-process.component.ts
  src/app/market/shared/orders/order-item/order-item.component.ts
  src/app/modals/market-bid-confirmation-modal/bid-confirmation-modal.component.html
  src/app/modals/market-bid-confirmation-modal/bid-confirmation-modal.component.scss
  src/app/modals/market-bid-confirmation-modal/bid-confirmation-modal.component.spec.ts
  src/app/modals/market-bid-confirmation-modal/bid-confirmation-modal.component.ts
  src/app/modals/market-place-order/place-order.component.html
  src/app/modals/market-place-order/place-order.component.scss
  src/app/modals/market-place-order/place-order.component.spec.ts
  src/app/modals/market-place-order/place-order.component.ts
  src/app/modals/market-shipping/shipping.component.html
  src/app/modals/market-shipping/shipping.component.scss
  src/app/modals/market-shipping/shipping.component.spec.ts
  src/app/modals/market-shipping/shipping.component.ts
  src/app/modals/modals.module.ts
Labels: ready for review

#1088 Created select-search component to fixed Select box filter issue.
  src/app/core-ui/material/mat-otpgroup-select-search/mat-otpgroup-select-search.component.html
  src/app/core-ui/material/mat-otpgroup-select-search/mat-otpgroup-select-search.component.scss
  src/app/core-ui/material/mat-otpgroup-select-search/mat-otpgroup-select-search.component.spec.ts
  src/app/core-ui/material/mat-otpgroup-select-search/mat-otpgroup-select-search.component.ts
  src/app/core-ui/material/mat-select-search/mat-select-search.component.html
  src/app/core-ui/material/mat-select-search/mat-select-search.component.scss
  src/app/core-ui/material/mat-select-search/mat-select-search.component.spec.ts
  src/app/core-ui/material/mat-select-search/mat-select-search.component.ts
  src/app/core-ui/material/material.module.ts
  src/app/core/market/api/category/category.service.ts
  src/app/core/market/market-state/market-state.service.ts
  src/app/market/buy/checkout-process/checkout-process.component.html
  src/app/market/buy/checkout-process/checkout-process.component.ts
  src/app/market/listings/listings.component.html
  src/app/market/listings/listings.component.scss
  src/app/market/listings/listings.component.ts
  src/app/market/sell/add-item/add-item.component.html
  src/app/market/sell/add-item/add-item.component.ts
  src/assets/scss/_material-components.scss
Labels: ready for review

#1090 Accept terms
  modules/close-gui/close-gui.js
  modules/init.js
  preload.js
  src/app/core-ui/main/main-view.component.ts
  src/app/core-ui/main/main-view.module.ts
  src/app/core/close-gui/close-gui.service.spec.ts
  src/app/core/close-gui/close-gui.service.ts
  src/app/core/core.module.ts
  src/app/modals/modals-helper.service.ts
  src/app/modals/modals.module.ts
  src/app/modals/terms/terms-txt.ts
  src/app/modals/terms/terms.component.html
  src/app/modals/terms/terms.component.scss
  src/app/modals/terms/terms.component.spec.ts
  src/app/modals/terms/terms.component.ts
  src/app/modals/terms/terms.service.spec.ts
  src/app/modals/terms/terms.service.ts
Labels: needs-testing

#1081 total count on left menu for each buy/sell according to status
  src/app/core-ui/main/main-view.component.html
  src/app/core-ui/main/main-view.component.scss
  src/app/core-ui/main/main-view.component.ts
  src/app/core-ui/main/main-view.module.ts
  src/app/core-ui/main/order-count/order-count.component.html
  src/app/core-ui/main/order-count/order-count.component.scss
  src/app/core-ui/main/order-count/order-count.component.spec.ts
  src/app/core-ui/main/order-count/order-count.component.ts
  src/app/core/market/api/bid/bid.model.ts
  src/app/core/market/api/bid/bid.service.ts
  src/app/core/market/api/bid/order.model.ts
  src/app/core/market/market-state/market-state.service.ts
  src/app/core/market/market.module.ts
  src/app/core/market/order-status-notifier/order-status-notifier.service.spec.ts
  src/app/core/market/order-status-notifier/order-status-notifier.service.ts
  src/app/core/notification/notification.service.ts
  src/app/market/buy/buy.component.html
  src/app/market/sell/sell.component.html
  src/assets/scss/_material-components.scss
Labels: ready for review
