Repository particl/particl-desktop, pull requests merged in 2019-03, with the labels that each got.

#1478 - Fixed the wiki link opne in new browser issue.
  src/app/wallet/proposals/add-proposal/add-proposal.component.html
  src/app/wallet/wallet/send/send.component.html
  yarn.lock
Labels: ready for review, release: mainnet alpha

#1469 - Added the expiry time and processing related changes.
  src/app/wallet/proposals/models/proposal.model.ts
  src/app/wallet/proposals/proposal-details/proposal-details.component.html
  src/app/wallet/proposals/proposals.component.ts
Labels: ready for review, release: mainnet alpha

#1477 Creates separation between mainnet and testnet particld binaries used
  main.js
  modules/clientBinaries/clientBinariesManager.js
  modules/daemon/daemon.js
  modules/daemon/daemonManager.js
  modules/daemon/update.js
  modules/init.js
  modules/market/market.js
  package.json
  src/app/core/rpc/rpc.service.ts
  src/environments/environment.test.ts
  yarn.lock
Labels: ready for review, release: mainnet alpha

#1480 Listing expiry time set as default 2 days.
  src/app/modals/market-listing-expiration/listing-expiration.component.ts
  src/app/wallet/proposals/add-proposal/add-proposal.component.ts
Labels: ready for review, release: mainnet alpha

#1487 logo(s) update
  src/app/core-ui/main/main-view.component.scss
  src/assets/particl-logo-symbol.svg
  src/assets/particl-logo-testnet.svg
  src/assets/particl-logo-white-bg.svg
  src/assets/particl-logo-xmas.svg
  src/assets/particl-logo.svg
Labels: release: mainnet alpha

#1494 GFX: updated icons
  background-mac.png
  download-button.png
  src/assets/icons/logo-150x150.png
  src/assets/icons/logo-16x16.png
  src/assets/icons/logo-32x32.png
  src/assets/icons/logo.icns
  src/assets/icons/logo.ico
  src/assets/icons/logo.png
  src/assets/icons/notification.png
Labels: ready for review, release: mainnet alpha

#1485 Adjusts configuration for marketplace to startup correctly on mainnet
  karma.conf.js
  main.js
  modules/clientBinaries/clientBinariesManager.js
  modules/daemon/daemonConfig.js
  modules/daemon/daemonManager.js
  modules/daemon/update.js
  modules/init.js
  modules/market/market.js
  modules/options.js
  modules/rpc/rpc.js
  modules/webrequest/http-auth.js
  preload.js
  src/app/_test/core-test/rpc-test/mock-data/listunspent.mock.ts
  src/app/_test/core-test/rpc-test/rpc-mock.service.ts
  src/app/_test/core-test/rpc-test/rpc-state-mock.service.ts
  src/app/core/http/client-version.service.ts
  src/app/core/rpc/rpc-state/rpc-state.service.ts
  src/app/core/rpc/rpc.service.ts
  src/app/wallet/wallet/send/send.component.spec.ts
  src/environments/environment.prod.ts
Labels: ready for review, release: mainnet alpha

#1483 accept & terms text updated
  src/app/modals/terms/terms-txt.ts
  src/app/modals/terms/terms.component.html
  src/app/modals/terms/terms.component.scss
Labels: ready for review, release: mainnet alpha

#1513 - Advance options and pay to sections related fixes
  src/app/wallet/wallet/send/send.component.html
  src/app/wallet/wallet/send/send.component.ts
Labels: ready for review, release: mainnet alpha

#1506 Updates mainnet core version
  modules/clientBinaries/clientBinaries.json
  package.json
Labels: ready for review

#1453 added the actual balance on overview page
  src/app/core-ui/core-ui.module.ts
  src/app/core-ui/main/main-view.component.html
  src/app/core-ui/main/main-view.component.scss
  src/app/core-ui/main/main-view.module.ts
  src/app/core/rpc/rpc-state/rpc-state.service.ts
  src/app/market/listings/listing-item/listing-item.component.html
  src/app/market/listings/preview-listing/preview-listing.component.html
  src/app/wallet/overview/overview.component.html
  src/app/wallet/wallet/balances/balance.component.html
  src/app/wallet/wallet/balances/balance.component.scss
  src/app/wallet/wallet/balances/balance.component.ts
  src/app/wallet/wallet/send/send.component.html
  src/app/wallet/wallet/send/send.component.ts
  src/app/wallet/wallet/send/send.service.ts
  src/app/wallet/wallet/wallet.module.ts
Labels: release: mainnet alpha

#1533 Fixes the listing expiry option dropdown
  src/app/modals/market-listing-expiration/listing-expiration.component.html
  src/app/modals/market-listing-expiration/listing-expiration.component.ts
Labels: ready for review, release: mainnet alpha
